export const ORDER_CREATE_REQUEST = 'ORDER_CREATE_REQUEST'
export const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS'
export const ORDER_CREATE_FAILED = 'ORDER_CREATE_FAILED'

export const ORDER_DETAILS_REQUEST = 'ORDER_DETAILS_REQUEST'
export const ORDER_DETAILS_SUCCESS = 'ORDER_DETAILS_SUCCESS'
export const ORDER_DETAILS_FAILED = 'ORDER_DETAILS_FAILED'

export const ORDER_PAYMENT_REQUEST = 'ORDER_PAYMENT_REQUEST'
export const ORDER_PAYMENT_SUCCESS = 'ORDER_PAYMENT_SUCCESS'
export const ORDER_PAYMENT_FAILED = 'ORDER_PAYMENT_FAILED'
export const ORDER_PAYMENT_RESET = 'ORDER_PAYMENT_RESET'

export const ORDER_SHOW_USER_ORDERS_REQUEST = 'ORDER_SHOW_USER_ORDERS_REQUEST'
export const ORDER_SHOW_USER_ORDERS_SUCCESS = 'ORDER_SHOW_USER_ORDERS_SUCCESS'
export const ORDER_SHOW_USER_ORDERS_FAILED = 'ORDER_SHOW_USER_ORDERS_FAILED'
export const ORDER_SHOW_USER_ORDERS_RESET = 'ORDER_SHOW_USER_ORDERS_RESET'

export const ORDER_LIST_REQUEST = 'ORDER_LIST_REQUEST'
export const ORDER_LIST_SUCCESS = 'ORDER_LIST_SUCCESS'
export const ORDER_LIST_FAILED = 'ORDER_LIST_FAILED'

export const ORDER_PACKING_REQUEST = 'ORDER_PACKING_REQUEST'
export const ORDER_PACKING_SUCCESS = 'ORDER_PACKING_SUCCESS'
export const ORDER_PACKING_FAILED = 'ORDER_PACKING_FAILED'
export const ORDER_PACKING_RESET = 'ORDER_PACKING_RESET'

export const ORDER_IN_TRANSIT_REQUEST = 'ORDER_IN_TRANSIT_REQUEST'
export const ORDER_IN_TRANSIT_SUCCESS = 'ORDER_IN_TRANSIT_SUCCESS'
export const ORDER_IN_TRANSIT_FAILED = 'ORDER_IN_TRANSIT_FAILED'
export const ORDER_IN_TRANSIT_RESET = 'ORDER_IN_TRANSIT_RESET'

export const ORDER_DELIVERED_REQUEST = 'ORDER_DELIVERED_REQUEST'
export const ORDER_DELIVERED_SUCCESS = 'ORDER_DELIVERED_SUCCESS'
export const ORDER_DELIVERED_FAILED = 'ORDER_DELIVERED_FAILED'
export const ORDER_DELIVERED_RESET = 'ORDER_DELIVERED_RESET'
