export const ORDER_CREATE_REQUEST = 'ORDER_CREATE_REQUEST'
export const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS'
export const ORDER_CREATE_FAILED = 'ORDER_CREATE_FAILED'

export const ORDER_DETAILS_REQUEST = 'ORDER_DETAILS_REQUEST'
export const ORDER_DETAILS_SUCCESS = 'ORDER_DETAILS_SUCCESS'
export const ORDER_DETAILS_FAILED = 'ORDER_DETAILS_FAILED'

export const ORDER_PAYMENT_REQUEST = 'ORDER_PAYMENT_REQUEST'
export const ORDER_PAYMENT_SUCCESS = 'ORDER_PAYMENT_SUCCESS'
export const ORDER_PAYMENT_FAILED = 'ORDER_PAYMENT_FAILED'
export const ORDER_PAYMENT_RESET = 'ORDER_PAYMENT_RESET'

export const ORDER_SHOW_FOR_USER_REQUEST = 'ORDER_SHOW_FOR_USER_REQUEST'
export const ORDER_SHOW_FOR_USER_SUCCESS = 'ORDER_SHOW_FOR_USER_SUCCESS'
export const ORDER_SHOW_FOR_USER_FAILED = 'ORDER_SHOW_FOR_USER_FAILED'
